const commonFunction = require('@samming/common')
// const nodeModulesFunction = require('../index.js')
// const nodeModulesFunction = require('blahblahblah')
// const nodeModulesFunction = require('../../node_modules/index.js')

console.log(Object.keys(require.cache))
Object.keys(require.cache).forEach((key => {delete require.cache[key]}))
console.log(Object.keys(require.cache))
commonFunction()
console.log(Object.keys(require.cache))
Object.keys(require.cache).forEach((key => {delete require.cache[key]}))
console.log(Object.keys(require.cache))
module.paths.splice(module.paths.length,0,'我草泥马')
// console.log(Object.keys(require.cache))
// console.log(module.paths)
// console.log(module)